services:
  app1:
    build: ./app1-nginx
    image: custom-nginx:1.0
    container_name: app1
    ports:
      - "8081:80"

  app2:
    build: ./app2-apache
    image: custom-apache:1.0
    container_name: app2
    ports:
      - "8082:80"

  app3:
    image: redis:7
    container_name: app3
    ports:
      - "6379:6379"

  app4:
    image: postgres:14
    container_name: app4
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app5:
    build: ./app5-alpine
    image: alpine-worker:1.0
    container_name: app5

volumes:
  pgdata:
