apiVersion: v1
kind: ConfigMap
metadata:
  name: green-configmap
  namespace: blue-green-ns
data:
  index.html: |
    <html>
    <head><title>Green Deployment</title></head>
    <body>
      <h1>This traffic is routed from GREEN deployment</h1>
    </body>
    </html>
