apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: blue-green-ns
spec:
  selector:
    app: blue-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  
  type: ClusterIP
          