apiVersion: v1
kind: Service
metadata:
  name: rolling-update-service
  namespace: rolling-update-ns  
spec:
  selector: 
    app: rolling-update-demo  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
                  